version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    image: callmebot_web
    command: /start
    volumes: 
      - .:/application
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - APP_ENV=${APP_ENV?err}
    depends_on:
      - redis
      - db

  db: 
    build: 
      context: ./compose/local/db
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=callmebot
      - POSTGRES_PASSWORD=callmebot
    ports:
      - "5432:5432"
    expose:
      - 5432

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data

  celery_worker:
      build:
        context: .
        dockerfile: ./compose/local/flask/Dockerfile
      image: callmebot_celery_worker
      command: /start-celeryworker
      volumes:
        - .:/application
      env_file:
        - .env
      environment:
        - APP_ENV=${APP_ENV?err}
      depends_on:
        - redis
        - db
      
  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    image: callmebot_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/application
    env_file:
      - .env
    environment:
      - APP_ENV=${APP_ENV?err}
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  redis_data: