"""rollback to 332e6859b41d

Revision ID: 596676a136dc
Revises: c40256a072de
Create Date: 2022-11-30 22:58:34.923206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596676a136dc'
down_revision = 'c40256a072de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
