"""try backref

Revision ID: c40256a072de
Revises: 332e6859b41d
Create Date: 2022-11-30 22:51:28.398731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40256a072de'
down_revision = '332e6859b41d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_constraint('reminder_author_id_fkey', type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('reminder_author_id_fkey', 'user', ['author_id'], ['id'])

    # ### end Alembic commands ###
