#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ -d "/application/migrations" ]; then
    python3 -m flask db migrate -m 'initial'
    python3 -m flask db upgrade
else 
    python3 -m flask db init
    python3 -m flask db upgrade
fi

gunicorn --bind 0.0.0.0:5000 'app:create_app()' --log-level DEBUG