#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

rm -rf migrations
python3 manager.py dropdb

python3 -m flask db init
python3 -m flask db migrate -m 'docker commit'
python3 -m flask db upgrade
python3 -m flask run --host=0.0.0.0
