#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

rm -rf migrations

python3 -m flask delete_versions
python3 -m flask db migrate -m 'docker commit'
python3 -m flask db upgrade
gunicorn --bind 0.0.0.0:5000 $FLASK_APP
